# 文档属性配置
site_name: mypy类型检查 # 文档标题
repo_name: hellowac/myppy-zh-cn
repo_url: https://github.com/hellowac/mypy-zh-cn
site_description: hellowac-类型检查

# 主题配置
theme:
        name: material # 主题
        language: zh # 主题语言: 中文简体
        custom_dir: overrides # 自定义文件夹
        palette:
                primary: teal # 主题色
                accent: blue # 提示颜色
        features:
                - header.autohide # 顶部导航栏自动隐藏
                - navigation.top # 回到顶部按钮
                - navigation.tabs # 导航栏顶部tab化
                - navigation.tabs.sticky # 顶部导航栏始终显示
                - navigation.path # 路径导航支持
                - content.tabs.link # 支持tab内容标题的锚点
                - content.code.copy # 代码块支持拷贝
                - content.tooltips # 工具提示
                - navigation.indexes # 分组标题导航到index页面
                - navigation.prune # 导航修剪
                - navigation.instant # 即时加载

# 插件
plugins:
        - search # 搜索支持
        - mike # 支持文档版本化
        - autorefs # 锚点跨md文档支持
        - glightbox # 照片点击放大支持, 依赖Python包: mkdocs-glightbox
        # - mkdocstrings: # 支持从项目中生成文档, 依赖python包: mkdocstrings , https://github.com/mkdocstrings/mkdocstrings
        #           default_handler: python # 默认处理语言, 更多选项参考: https://mkdocstrings.github.io/usage/
        #           handlers:
        #                   python:
        #                           paths: [..] # 查找的模块，在上一级目录
        #                           options:
        #                                   show_bases: true # 显示继承的类
        #                                   show_root_heading: true # 显示顶级标题
        #                                   show_root_members_full_path: true # 显示顶级下面成员的全路径
        #                                   show_symbol_type_heading: true # 显示不同类标识符号
        #                                   members_order: "source" # 按成员在源文件中出现的顺序排序成员。
        #                                   merge_init_into_class: true # 是否将__init__方法合并到类的签名和文档字符串中
        #                                   show_if_no_docstring: false # 显示对象标题，即使它没有文档字符串或带有文档字符串的子项。
        #                                   show_signature: true # 显示方法和函数签名。
        #                                   show_signature_annotations: True # 在方法和函数签名中显示类型注释。
        #                                   separate_signature: True # 是否将整个签名放在标题下方的代码块中。
        #                                   docstring_section_style: table # 显示文档注释时的样式, list, https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_section_style
        #                                   docstring_style: google

        - git-revision-date-localized: # 支持文档创建时间显示， https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
                  locale: zh
                  enable_creation_date: true
                  type: date

# 监听文件变动的目录 https://mkdocstrings.github.io/usage/#watch-directories
watch:
        - . # 包含父级源码目录

# 扩展
extra:
        version: # 支持文档版本化
                provider: mike # mike 部署支持

extra_css:
        - stylesheets/extra.css

# 扩展支持， 支持数学符号
# extra_javascript:
#   - https://unpkg.com/mermaid@10.2.0/dist/mermaid.min.js
extra_javascript:
        - javascripts/mathjax.js
        - https://polyfill.io/v3/polyfill.min.js?features=es6
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# markdown内部扩展配置
markdown_extensions:
        - abbr # 工具提示 支持
        - admonition # 忠告 支持
        - codehilite
        - def_list # 指定定义列表, 就是名称冒号内容的方式
        - attr_list # 支持标签里面的 属性定义
        - footnotes # 脚注支持
        - pymdownx.caret # 插入符支持
        - pymdownx.mark # 标记支持
        - pymdownx.tilde # 代字号支持
        - pymdownx.details # 详情可折叠，支持, 依赖 admonition
        - pymdownx.inlinehilite # 行内高亮显示
        - pymdownx.snippets
        - markdown.extensions.toc: # https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml
                  slugify:
                          !!python/object/apply:pymdownx.slugs.slugify {
                                  kwds: {case: lower},
                          }
                  permalink: true
        - pymdownx.highlight: # 高亮显示代码块  https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
                  use_pygments: true
                  pygments_lang_class: true
                  noclasses: true
                  pygments_style: default
        - pymdownx.superfences: # 一些扩展功能的基础定义
                  custom_fences: # 代码块自定义
                          - name: mermaid # mermaid图表支持
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.tasklist: # 任务列表支持
                  custom_checkbox: true
        - pymdownx.tabbed: # 支持内容tab， 依赖 pymdownx.superfences
                  alternate_style: true
        - pymdownx.critic: # 突出显示内容
                  mode: view
        - pymdownx.keys # 键盘快捷键支持
        - pymdownx.smartsymbols # 智能符号
        - pymdownx.emoji: # emoji 表情支持  https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#emoji
                  emoji_index: !!python/name:material.extensions.emoji.twemoji
                  emoji_generator:
                          !!python/name:material.extensions.emoji.to_svg # 页面导航


        - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
                  generic: true

nav:
        - index.md
        - 第一步:
                  - mypy/index.md
                  - mypy/cheat_sheet_py3.md
                  - mypy/existing_code.md
        - 类型系统参考:
                  - 内置类型: mypy/builtin_types.md
                  - 类型推断和类型注解: mypy/type_inference_type_annotations.md
                  - 类型种类: mypy/kind_of_types.md
                  - 类的基础: mypy/class_basics.md
                  - 运行时的注解问题: mypy/annotation_issue_at_runtime.md
                  - 协议及其子类型: mypy/protocol_and_struct_subtyping.md
                  - 动态类型: mypy/dynamic_typing.md
                  - 类型收缩: mypy/type_narrowing.md
                  - 鸭子类型兼容: mypy/duck_type_compatibility.md
                  - 存根文件: mypy/stub_files.md
                  - 泛型: mypy/generics.md
                  - 更多类型: mypy/more_types.md
                  - 字面量和枚举: mypy/literal_and_enum.md
                  - 类型字典: mypy/typeddict.md
                  - 最终名称、方法和类: mypy/final_names_methods_classes.md
                  - 元类: mypy/metaclasses.md
        - 配置和运行mypy:
                  - mypy_conf/index.md
                  - 运行mypy和管理导入: mypy_conf/running_mypy.md # https://mypy.readthedocs.io/en/stable/running_mypy.html
                  - mypy命令行: mypy_conf/command_line.md # https://mypy.readthedocs.io/en/stable/command_line.html
                  - mypy配置文件: mypy_conf/config_file.md # https://mypy.readthedocs.io/en/stable/config_file.html
                  - 内联配置: mypy_conf/inline_config.md # https://mypy.readthedocs.io/en/stable/inline_config.html
                  - mypy服务(守护进程): mypy_conf/mypy_daemon.md # https://mypy.readthedocs.io/en/stable/mypy_daemon.html
                  - 使用安装包: mypy_conf/installed_packages.md # https://mypy.readthedocs.io/en/stable/installed_packages.html
                  - 扩展和集成 mypy: mypy_conf/extending_mypy.md # https://mypy.readthedocs.io/en/stable/extending_mypy.html
                  - 自动存根生成: mypy_conf/stubgen.md # https://mypy.readthedocs.io/en/stable/stubgen.html
                  - 自动存根测试: mypy_conf/stubtest.md # https://mypy.readthedocs.io/en/stable/stubtest.html
        - 其他杂项:
                  - mypy_other/index.md
                  - 常见问题及解决办法: mypy_other/common_issues.md  # https://mypy.readthedocs.io/en/stable/common_issues.html
                  - 支持的 Python 特性: mypy_other/supported_python_features.md  # https://mypy.readthedocs.io/en/stable/supported_python_features.html
                  - 错误码: mypy_other/error_codes.md  # https://mypy.readthedocs.io/en/stable/error_codes.html
                  - 默认启用的错误码: mypy_other/error_code_list.md  # https://mypy.readthedocs.io/en/stable/error_code_list.html
                  - 可选检查的错误代码: mypy_other/error_code_list2.md  # https://mypy.readthedocs.io/en/stable/error_code_list2.html
                  - 额外特性: mypy_other/additional_features.md  # https://mypy.readthedocs.io/en/stable/additional_features.html
                  - 常见问题解答: mypy_other/faq.md  # https://mypy.readthedocs.io/en/stable/faq.html
        - 项目链接: mypy_other/project_links.md
